name: CI | Pizza planet 

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env: 
      DB_SERVER_DEVELOPMENT: ${{ secrets.DB_SERVER_DEVELOPMENT }}
      PRODUCTION_DB_NAME: ${{ secrets.PRODUCTION_DB_NAME }}
      PRODUCTION_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
      DB_SERVER_PRODUCTION: ${{ secrets.DB_SERVER_PRODUCTION }}
      
    steps:
      - name: Install Pizza planet
        uses: actions/checkout@v3

      - name: install Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: run flake8
        run : |
          flake8 app/ manage.py --exclude=app/test

      - name: show coverage
        run: |
          coverage run -m pytest app/test 
          coverage report -m
